apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: demo
spec:
  selector:
    app: webhook-receiver
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
